#!/usr/bin/env bash
[[ " tar:from tar:in help tar:help " == *" $1 "* ]] || exit $DOKKU_NOT_IMPLEMENTED_EXIT

case "$1" in
  tar:from)
    "$PLUGIN_AVAILABLE_PATH/tar/subcommands/from" "$@"
    ;;

  tar:in)
    "$PLUGIN_AVAILABLE_PATH/tar/subcommands/in" "$@"
    ;;

  help | tar:help)
    cat && cat<<EOF
    tar:in <app>, Reads an tarball containing the app from stdin
    tar:from <app> <url>, Loads an app tarball from url.
EOF
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac
