#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/tar/internal_functions"

main() {
  local APP="$1"; local REV="$2"

  # Don't trigger tar build if there is no tarball.
  if [[ ! -f "$DOKKU_ROOT/$APP/src.tar" ]]; then
    true
  else
    tar_build $APP
  fi
}

main "$@"
