#!/usr/bin/env bash
[[ " events events:on events:off events:list help events:help " == *" $1 "* ]] || exit $DOKKU_NOT_IMPLEMENTED_EXIT
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

case "$1" in
  events)
    "$PLUGIN_AVAILABLE_PATH/events/subcommands/default" "$@"
    ;;

  events:on)
    "$PLUGIN_AVAILABLE_PATH/events/subcommands/on" "$@"
    ;;

  events:off)
    "$PLUGIN_AVAILABLE_PATH/events/subcommands/off" "$@"
    ;;

  events:list)
    "$PLUGIN_AVAILABLE_PATH/events/subcommands/list" "$@"
    ;;

  help | events:help)
    cat && cat<<EOF
    events [-t], Show the last events (-t follows)
    events:list, List logged events
    events:on, Enable events logger
    events:off, Disable events logger
EOF
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac

