#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

main() {
  declare cmd="events"
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  set -- $cmd $@

  if [[ -f $DOKKU_EVENTS_LOGFILE ]]; then
    if [[ $2 == "-t" ]]; then
      tail -F $DOKKU_EVENTS_LOGFILE
    else
      tail -n 100 $DOKKU_EVENTS_LOGFILE
    fi
  fi
}

main "$@"
