#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

main() {
  declare cmd="events:list"
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  set -- $cmd $@

  local PLUGIN_DIR="$(dirname $0)/"
  if [[ "$DOKKU_EVENTS" ]]; then
    logged="$(find $PLUGIN_DIR -type l -printf '%f ' | sort)"
    dokku_col_log_info2_quiet "Events currently logged"
    for hook in $logged; do
      dokku_col_log_msg "$hook"
    done
  else
    dokku_log_warn "Events logger disabled"
  fi
}

main "$@"
