#!/usr/bin/env bash
[[ " nginx:build-config nginx:access-logs nginx:error-logs nginx:disable nginx:enable help nginx:help " == *" $1 "* ]] || exit $DOKKU_NOT_IMPLEMENTED_EXIT

case "$1" in
  nginx:build-config)
    "$PLUGIN_AVAILABLE_PATH/nginx-vhosts/subcommands/build-config" "$@"
    ;;

  nginx:access-logs)
    "$PLUGIN_AVAILABLE_PATH/nginx-vhosts/subcommands/access-logs" "$@"
    ;;

  nginx:error-logs)
    "$PLUGIN_AVAILABLE_PATH/nginx-vhosts/subcommands/error-logs" "$@"
    ;;

  nginx:disable)
    "$PLUGIN_AVAILABLE_PATH/nginx-vhosts/subcommands/disable" "$@"
    ;;

  nginx:enable)
    "$PLUGIN_AVAILABLE_PATH/nginx-vhosts/subcommands/enable" "$@"
    ;;

  help | nginx:help)
    cat<<EOF
    nginx:build-config <app>, (Re)builds nginx config for given app
    nginx:access-logs <app> [-t], Show the nginx access logs for an application (-t follows)
    nginx:error-logs <app> [-t], Show the nginx error logs for an application (-t follows)
    nginx:disable <app>, Disable nginx for an application (forces container binding to external interface)
    nginx:enable <app>, Enable nginx for an application
EOF
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac
