#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

main() {
  declare cmd="domains:add"
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
  set -- $cmd $@

  local APP="$2"; verify_app_name "$APP"

  if [[ -z "${*:3}" ]]; then
    echo "Usage: dokku $1 $APP DOMAIN [DOMAIN ...]"
    echo "Must specify DOMAIN."
    exit 1
  fi

  if [[ $(egrep -w "^{$3}$" "$DOKKU_ROOT/$APP/VHOST" > /dev/null 2>&1; echo $?) -eq 0 ]]; then
    echo "$3 is already defined for $APP"
    exit 1
  fi

  shift 2
  dokku domains:setup $APP
  for DOMAIN in "$@"; do
    echo "$DOMAIN" >> "$DOKKU_ROOT/$APP/VHOST"
  done
  plugn trigger post-domains-update $APP "add" "$@"
  for DOMAIN in "$@"; do
    dokku_log_info1 "Added $DOMAIN to $APP"
  done
}

main "$@"
