#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

main() {
  declare cmd="domains:clear"
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
  set -- $cmd $@

  local APP="$2"; verify_app_name "$APP"

  rm -f "$DOKKU_ROOT/$APP/VHOST"
  dokku domains:setup $APP
  plugn trigger post-domains-update $APP "clear"
  dokku_log_info1 "Cleared domains in $APP"
}

main "$@"
