#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/domains/functions"

main() {
  declare cmd="domains"
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
  set -- $cmd $@

  local APP="$2"; verify_app_name "$APP"

  dokku domains:setup $APP
  if [[ -f "$DOKKU_ROOT/$APP/VHOST" ]]; then
    dokku_log_info2_quiet "$APP Domain Names"
    get_app_domains "$APP"
  else
    dokku_log_fail "No domain names set for $APP"
  fi
}

main "$@"
