#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

main() {
  declare cmd="domains:remove"
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
  set -- $cmd $@

  local APP="$2"; verify_app_name "$APP"

  if [[ -z "${*:3}" ]]; then
    echo "Usage: dokku $1 $APP DOMAIN [DOMAIN ...]"
    echo "Must specify DOMAIN."
    exit 1
  fi

  shift 2
  dokku domains:setup $APP
  for DOMAIN in "$@"; do
    sed -i "/^$DOMAIN$/d" "$DOKKU_ROOT/$APP/VHOST"
  done
  plugn trigger post-domains-update $APP "remove" "$@"
  for DOMAIN in "$@"; do
    dokku_log_info1 "Removed $DOMAIN from $APP"
  done
}

main "$@"
