#!/usr/bin/env bash
[[ " backup:export backup:import help backup:help " == *" $1 "* ]] || exit $DOKKU_NOT_IMPLEMENTED_EXIT

case "$1" in
  backup:export)
    "$PLUGIN_AVAILABLE_PATH/backup/subcommands/export" "$@"
    ;;

  backup:import)
    "$PLUGIN_AVAILABLE_PATH/backup/subcommands/import" "$@"
    ;;

  help | backup:help)
    cat<<EOF
    backup:export [file], Export dokku configuration files
    backup:import [file], Import dokku configuration files
EOF
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac
