#!/usr/bin/env bash
[[ " config config:get config:set config:unset help config:help " == *" $1 "* ]] || exit $DOKKU_NOT_IMPLEMENTED_EXIT

case "$1" in
  config)
    "$PLUGIN_AVAILABLE_PATH/config/subcommands/default" "$@"
    ;;

  config:get)
    "$PLUGIN_AVAILABLE_PATH/config/subcommands/get" "$@"
    ;;

  config:set)
    "$PLUGIN_AVAILABLE_PATH/config/subcommands/set" "$@"
    ;;

  config:unset)
    "$PLUGIN_AVAILABLE_PATH/config/subcommands/unset" "$@"
    ;;

  help | config:help)
    cat<<EOF
    config (<app>|--global), Display all global or app-specific config vars
    config:get (<app>|--global) KEY, Display a global or app-specific config value
    config:set (<app>|--global) KEY1=VALUE1 [KEY2=VALUE2 ...], Set one or more config vars
    config:unset (<app>|--global) KEY1 [KEY2 ...], Unset one or more config vars
EOF
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac
