#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

main() {
  declare cmd="apps:destroy"
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
  set -- $cmd $@

  local APP="$2"; verify_app_name "$APP"
  [[ "$2" == "tls" ]] && dokku_log_fail "Unable to destroy tls directory"
  [[ "$3" == "force" ]] && DOKKU_APPS_FORCE_DELETE=1
  local IMAGE_TAG=$(get_running_image_tag $APP)

  if [[ -z "$DOKKU_APPS_FORCE_DELETE" ]]; then
    dokku_log_warn "WARNING: Potentially Destructive Action"
    dokku_log_warn "This command will destroy $APP (including all add-ons)."
    dokku_log_warn "To proceed, type \"$APP\""
    echo ""

    read -rp "> " app_name
    if [[ "$app_name" != "$APP" ]]; then
      dokku_log_fail "Confirmation did not match $APP. Aborted."
    fi
  fi

  echo "Destroying $APP (including all add-ons)"

  plugn trigger pre-delete $APP $IMAGE_TAG
  DOKKU_APP_CIDS=$(get_app_container_ids $APP)
  if [[ -n $DOKKU_APP_CIDS ]]; then
    for ID in $DOKKU_APP_CIDS; do
      docker stop $ID > /dev/null || true
      docker rm $ID  > /dev/null || true
    done
  fi

  plugn trigger post-delete $APP $IMAGE_TAG
}

main "$@"
