#!/usr/bin/env bash
[[ " domains domains:setup domains:add domains:clear domains:remove help domains:help " == *" $1 "* ]] || exit $DOKKU_NOT_IMPLEMENTED_EXIT

case "$1" in
  domains)
    "$PLUGIN_AVAILABLE_PATH/domains/subcommands/default" "$@"
    ;;

  domains:setup)
    "$PLUGIN_AVAILABLE_PATH/domains/subcommands/setup" "$@"
    ;;

  domains:add)
    "$PLUGIN_AVAILABLE_PATH/domains/subcommands/add" "$@"
    ;;

  domains:clear)
    "$PLUGIN_AVAILABLE_PATH/domains/subcommands/clear" "$@"
    ;;

  domains:remove)
    "$PLUGIN_AVAILABLE_PATH/domains/subcommands/remove" "$@"
    ;;

  help | domains:help)
    cat<<EOF
    domains <app>, List custom domains for app
    domains:add <app> DOMAIN, Add a custom domain to app
    domains:clear <app>, Clear all custom domains for app
    domains:remove <app> DOMAIN, Remove a custom domain from app
EOF
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac
