#!/usr/bin/env bash
[[ " tags tags:create tags:deploy tags:destroy help tags:help " == *" $1 "* ]] || exit $DOKKU_NOT_IMPLEMENTED_EXIT

case "$1" in
  tags)
    "$PLUGIN_AVAILABLE_PATH/tags/subcommands/default" "$@"
    ;;

  tags:create)
    "$PLUGIN_AVAILABLE_PATH/tags/subcommands/create" "$@"
    ;;

  tags:deploy)
    "$PLUGIN_AVAILABLE_PATH/tags/subcommands/deploy" "$@"
    ;;

  tags:destroy)
    "$PLUGIN_AVAILABLE_PATH/tags/subcommands/destroy" "$@"
    ;;

  help | tags:help)
    cat && cat<<EOF
    tags <app>, List all app image tags
    tags:create <app> <tag>, Add tag to latest running app image
    tags:deploy <app> <tag>, Deploy tagged app image
    tags:destroy <app> <tag>, Remove app image tag
EOF
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac
