#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/docker-options/internal_functions"

main() {
  declare cmd="docker-options:add"
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
  set -- $cmd $@

  local APP="$2"; verify_app_name "$APP"

  get_app $2
  get_phases $3
  shift 3 # everything else passed is the docker option
  get_passed_docker_option "$@"
  add_passed_docker_option passed_phases[@] "${passed_docker_option[@]}"
}

main "$@"
