#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/docker-options/internal_functions"

main() {
  declare cmd="docker-options"
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
  set -- $cmd $@

  local APP="$2"; verify_app_name "$APP"

  get_app $2
  get_phases $3
  if [[ ! "${passed_phases[@]}" ]]; then
    display_all_phases_options
  else
    display_passed_phases_options passed_phases[@]
  fi
}

main "$@"
