#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

main() {
  declare cmd="certs:remove"
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
  set -- $cmd $@

  local APP="$2"; verify_app_name "$APP"
  local APP_SSL_PATH="$DOKKU_ROOT/$APP/tls"

  if [[ -d "$APP_SSL_PATH" ]]; then
    dokku_log_info1 "Removing SSL endpoint from $APP"
    rm -rf $APP_SSL_PATH
    plugn trigger post-domains-update $APP
  else
    dokku_log_fail "An app-specific SSL endpoint is not defined"
  fi
}

main "$@"
