#!/usr/bin/env bash
[[ " plugin plugin:install plugin:install-dependencies plugin:update plugin:disable plugin:enable plugin:uninstall help plugin:help " == *" $1 "* ]] || exit $DOKKU_NOT_IMPLEMENTED_EXIT

case "$1" in
  plugin)
    "$PLUGIN_AVAILABLE_PATH/plugin/subcommands/default" "$@"
    ;;

  plugin:install)
    "$PLUGIN_AVAILABLE_PATH/plugin/subcommands/install" "$@"
    ;;

  plugin:install-dependencies)
    "$PLUGIN_AVAILABLE_PATH/plugin/subcommands/install-dependencies" "$@"
    ;;

  plugin:update)
    "$PLUGIN_AVAILABLE_PATH/plugin/subcommands/update" "$@"
    ;;

  plugin:disable)
    "$PLUGIN_AVAILABLE_PATH/plugin/subcommands/disable" "$@"
    ;;

  plugin:enable)
    "$PLUGIN_AVAILABLE_PATH/plugin/subcommands/enable" "$@"
    ;;

  plugin:uninstall)
    "$PLUGIN_AVAILABLE_PATH/plugin/subcommands/uninstall" "$@"
    ;;

  help | plugin:help)
    cat<<EOF
    plugin, Print active plugins
    plugin:install [--core|git-url [--committish tag|branch|commit|--name custom-plugin-name]], Optionally download git-url (with custom tag/committish) & run install trigger for active plugins (or only core ones)
    plugin:install-dependencies [--core], Run install-dependencies trigger for active plugins (or only core ones)
    plugin:update [name [committish]], Optionally update named plugin from git (with custom tag/committish) & run update trigger for active plugins
    plugin:enable <name>, Enable a previously disabled plugin
    plugin:disable <name>, Disable an installed plugin (third-party only)
    plugin:uninstall <name>, Uninstall a plugin (third-party only)
EOF
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac


