#!/usr/bin/env bash
[[ " apps apps:create apps:rename apps:destroy help apps:help " == *" $1 "* ]] || exit $DOKKU_NOT_IMPLEMENTED_EXIT

case "$1" in
  apps)
    "$PLUGIN_AVAILABLE_PATH/apps/subcommands/default" "$@"
    ;;

  apps:create)
    "$PLUGIN_AVAILABLE_PATH/apps/subcommands/create" "$@"
    ;;

  apps:rename)
    "$PLUGIN_AVAILABLE_PATH/apps/subcommands/rename" "$@"
    ;;

  apps:destroy)
    "$PLUGIN_AVAILABLE_PATH/apps/subcommands/destroy" "$@"
    ;;

  help | apps:help)
    cat<<EOF
    apps, List your apps
    apps:create <app>, Create a new app
    apps:destroy <app>, Permanently destroy an app
    apps:rename <old-app> <new-app>, Rename an app
EOF
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac
