#!/usr/bin/env bash
[[ " shell help shell:help " == *" $1 "* ]] || exit $DOKKU_NOT_IMPLEMENTED_EXIT

case "$1" in
  shell)
    "$PLUGIN_AVAILABLE_PATH/shell/subcommands/_default" "$@"
    ;;

  help | shell:help)
    cat<<EOF
    shell, Spawn dokku shell
EOF
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac
