#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

main() {
  declare cmd="plugin"
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  set -- $cmd $@

  plugn list
}

main "$@"
