#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/plugin/functions"

main() {
  declare cmd="plugin:disable"
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  set -- $cmd $@

  [[ -z $2 ]] && dokku_log_fail "Please specify a plugin to disable"
  local PLUGIN="$2"
  disable_plugin "$PLUGIN"
}

main "$@"
