#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/plugin/functions"

main() {
  declare cmd="plugin:install"
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  set -- $cmd $@

  case "$2" in
    --core)
      [[ "$#" -gt 2 ]] && dokku_log_info1_quiet "Cannot install additional core plugins, running core plugin install trigger"
      PLUGIN_PATH="$PLUGIN_CORE_PATH" plugn trigger install
      ;;
    https:*|git:*|ssh:*)
      shift
      download_and_enable_plugin "$@"
      plugn trigger install
      ;;
    *)
      plugn trigger install
      ;;
  esac
}

main "$@"
