#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

main() {
  declare cmd="plugin:install-dependencies"
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  set -- $cmd $@

  if [[ $2 == "--core" ]]; then
    PLUGIN_PATH="$PLUGIN_CORE_PATH" plugn trigger dependencies
  else
    plugn trigger dependencies
  fi
}

main "$@"
