#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

main() {
  declare cmd="plugin:update"
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  set -- $cmd $@

  if [[ -n "$2" ]]; then
    local PLUGIN="$2"
    local PLUGIN_COMMITTISH="$3"
    plugn update "$PLUGIN" "$PLUGIN_COMMITTISH"
  fi
  plugn trigger update
}

main "$@"
