#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$1" in
  logs)
    "$PLUGIN_AVAILABLE_PATH/logs/subcommands/default" "$@"
    ;;

  help | logs:help)
    cat<<EOF
    logs <app> [-h] [--num num] [--ps process] [--quiet] [--tail], Show the last logs for an application
EOF
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac
