#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/tags/functions"

main() {
  declare cmd="tags:create"
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
  set -- $cmd $@

  local APP="$2"; verify_app_name "$APP"
  local IMAGE_TAG="$3";
  local IMAGE_REPO=$(get_app_image_repo $APP)

  tag_image "$IMAGE_REPO:latest" "$IMAGE_REPO:$IMAGE_TAG"
  dokku_log_info2_quiet "Added $IMAGE_TAG tag to $IMAGE_REPO"
  plugn trigger tags-create $APP $IMAGE_TAG
}

main "$@"
