#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

main() {
  declare cmd="tags:destroy"
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
  set -- $cmd $@

  local APP="$2"; verify_app_name "$APP"
  local IMAGE_TAG="$3";
  local IMAGE_REPO=$(get_app_image_repo $APP)

  case "$IMAGE_TAG" in
    latest)
      dokku_log_fail "You can't remove internal dokku tag ($IMAGE_TAG) for $IMAGE_REPO"
      ;;

    *)
      docker rmi "$IMAGE_REPO:$IMAGE_TAG"
      ;;
  esac
  plugn trigger tags-destroy $APP $IMAGE_TAG
}

main "$@"
