#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

main() {
  declare cmd="ps"
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
  set -- $cmd $@

  local APP="$2"; verify_app_name "$APP"
  ! (is_deployed $APP) && echo "App $APP has not been deployed" && exit 0

  local DOKKU_APP_RUNNING_CONTAINER_IDS=$(get_app_running_container_ids $APP)
  local DOKKU_RUN_OPTS=""

  for CID in $DOKKU_APP_RUNNING_CONTAINER_IDS; do
    has_tty && DOKKU_RUN_OPTS+="-i -t"
    dokku_log_info1_quiet "running processes in container: $CID"
    docker exec $DOKKU_RUN_OPTS $CID /bin/sh -c "ps auxwww"
  done
}

main "$@"
