#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

main() {
  declare cmd="ps:restartall"
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  set -- $cmd $@

  shopt -s nullglob
  for app in $(dokku_apps); do
    dokku ps:restart $app
  done
  shopt -u nullglob
}

main "$@"
