#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/ps/functions"

main() {
  declare cmd="ps:scale"
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
  set -- $cmd $@

  local APP="$2"; verify_app_name "$APP"
  local IMAGE_TAG=$(get_running_image_tag $APP)
  local DOKKU_SCALE_FILE="$DOKKU_ROOT/$APP/DOKKU_SCALE"
  shift 2

  [[ ! -e $DOKKU_SCALE_FILE ]] && generate_scale_file "$APP" "$IMAGE_TAG"
  if [[ -z "$@" ]]; then
    dokku_log_info1_quiet "Scaling for $APP"
    dokku_col_log_info1_quiet "proctype" "qty"
    dokku_col_log_info1_quiet "--------" "---"
    while read -r line || [[ -n "$line" ]]; do
      [[ -z "$line" ]] && continue
      local PROC_NAME=${line%%=*}
      local PROC_COUNT=${line#*=}
      dokku_col_log_info1 "$PROC_NAME" "$PROC_COUNT"
    done < "$DOKKU_SCALE_FILE"
  else
    set_scale "$APP" "$@"
    release_and_deploy "$APP" "$IMAGE_TAG"
  fi
}

main "$@"
