#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

main() {
  declare cmd="ps:start"
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
  set -- $cmd $@

  local APP="$2"; verify_app_name "$APP"
  local IMAGE_TAG=$(get_running_image_tag $APP);

  ! (is_deployed $APP) && echo "App $APP has not been deployed" && exit 0

  if ! (is_app_running $APP); then
    release_and_deploy "$APP" "$IMAGE_TAG"
  else
    echo "App $APP already running"
  fi
}

main "$@"
