#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"
source "$PLUGIN_AVAILABLE_PATH/nginx-vhosts/functions"

main() {
  declare cmd="nginx:enable"
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
  set -- $cmd $@

  local APP="$2"; verify_app_name "$APP"

  if [[ "$(is_app_nginx_enabled $APP)" == "false" ]]; then
    config_unset --no-restart $APP DOKKU_NO_NGINX NO_VHOST
    unset DOKKU_NO_NGINX NO_VHOST
    nginx_build_config $APP
  else
    dokku_log_info1 "nginx is already enabled for app ($APP)"
  fi
}

main "$@"
