#!/usr/bin/env bash
[[ " docker-options docker-options:add docker-options:remove help docker-options:help " == *" $1 "* ]] || exit $DOKKU_NOT_IMPLEMENTED_EXIT

case "$1" in
  docker-options)
    "$PLUGIN_AVAILABLE_PATH/docker-options/subcommands/default" "$@"
    ;;

  docker-options:add)
    "$PLUGIN_AVAILABLE_PATH/docker-options/subcommands/add" "$@"
    ;;

  docker-options:remove)
    "$PLUGIN_AVAILABLE_PATH/docker-options/subcommands/remove" "$@"
    ;;

  help | docker-options:help)
    cat<<EOF
    docker-options <app>, Display app's Docker options for all phases
    docker-options <app> <phase(s)>, Display app's Docker options for phase (comma separated phase list)
    docker-options:add <app> <phase(s)> OPTION, Add Docker option to app for phase (comma separated phase list)
    docker-options:remove <app> <phase(s)> OPTION, Remove Docker option from app for phase (comma separated phase list)
EOF
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac
