#!/usr/bin/env bash
[[ " enter help enter:help " == *" $1 "* ]] || exit $DOKKU_NOT_IMPLEMENTED_EXIT

case "$1" in
  enter)
    "$PLUGIN_AVAILABLE_PATH/enter/subcommands/default" "$@"
    ;;

  help | enter:help)
    cat && cat<<EOF
    enter <app> [<container-type> || --container-id <container-id>], Connect to a specific app container
EOF
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;

esac
